### ISSUE TITLE
Create a Storage Account Module for Azure in Terraform `azure-sa-backup`

### ISSUE THREAD

**Issue by jcframil** [prefapp/tfm#286]
# Description :writing_hand: 

We need to develop a Terraform module that simplifies the provisioning and management of Azure Storage Accounts Backups. The module should allow for the creation and configuration of all necessary resources related to a storage account backups, including blobs and shares.

# Requirements :receipt: 

The module should support the creation of different types of storage accounts backups for blobs and shares, and network related resources

# Resource Configurations :wrench: 
The module should allow for configuring the following resources:

- [azurerm_recovery_services_vault.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/recovery_services_vault)
- [azurerm_backup_container_storage_account.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_container_storage_account)
- [azurerm_backup_policy_file_share.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_file_share)
- [azurerm_backup_protected_file_share.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_protected_file_share)
- [azurerm_data_protection_backup_vault.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_vault)
- [azurerm_role_assignment.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment)
- [azurerm_data_protection_backup_policy_blob_storage.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_policy_blob_storage)
- [azurerm_data_protection_backup_instance_blob_storage.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_instance_blob_storage)
- [azurerm_storage_management_policy.this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_management_policy)

# Input Variables :1234: 

```yaml
    values:
      # General values
      resource_group_name: "test-rg"
      storage_account_id: "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx"

      # Backup share values
      backup_share:
        policy_name: "daily-backup-policy"
        recovery_services_vault_name: "test-vault"
        sku: "Standard"
        soft_delete_enabled: true
        storage_mode_type: "GeoRedundant"
        cross_region_restore_enabled: true
        source_file_share_name:
          - "datadir"
        identity:
          type: "SystemAssigned"
        encryption:
          key_id: null
          infrastructure_encryption_enabled: false
          user_assigned_identity_id: null
          use_system_assigned_identity: false
        timezone: "UTC"
        backup:
          frequency: "Daily"
          time: "02:00"
        retention_daily:
          count: 7
        retention_weekly:
          count: 4
          weekdays:
          - "Sunday"
        retention_monthly:
          count: 12
          weekdays:
          - "Sunday"
          weeks:
          - "First"
        retention_yearly:
          count: 5
          weekdays:
          - "Sunday"
          weeks:
          - "First"
          months:
          - "January"

      # Backup blob values
      backup_blob:
        vault_name: "test-vault"
        datastore_type: "AzureBlob"
        redundancy: "GRS"
        identity_type: "SystemAssigned"
        role_assignment: "StorageBlobDataContributor"
        policy:
          name: "daily-blob-backup-policy"
          vault_id: "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vaults/test-vault"
          backup_repeating_time_intervals:
          - "R/2023-01-01T02:00:00Z/P1D"
          operational_default_retention_duration: "P30D"
          retention_rule:
          - name: "daily-retention"
            duration: "P30D"
            criteria:
            absolute_criteria: null
            days_of_month: null
            days_of_week:
              - "Sunday"
            months_of_year: null
            scheduled_backup_times: null
            weeks_of_month: null
            life_cycle:
            data_store_type: "VaultStore"
            duration: "P30D"
            priority: 1
          time_zone: "UTC"
          vault_default_retention_duration: "P30D"
          retention_duration: "P30D"
          instance_blob_name: "datadir"

      # Lifecycle storage account policy values
      lifecycle_policy_rule:
      - name: "delete-old-versions"
        enabled: true
        filters:
        prefix_match:
          - "datadir"
        blob_types:
          - "blockBlob"
        actions:
        base_blob:
          delete_after_days_since_creation_greater_than: 365
        snapshot:
          delete_after_days_since_creation_greater_than: 365
        version:
          delete_after_days_since_creation: 365
```

# Output Variables :1234: 
None

# Documentation :book: 
Provide comprehensive documentation including examples for different use cases (e.g., file storage,  blobs and shares, identity, etc.)

# Acceptance Criteria: :heavy_check_mark: 
The module is tested and validated with different configurations.
Code is well-structured, following Terraform best practices.
Comprehensive documentation and usage examples are provided.
```[tasklist]
### Tasks
- [ ] https://github.com/prefapp/tfm/pull/287
```

```[tasklist]
### Tasks
- [x] Allow references to [azure-sa module](https://github.com/prefapp/tfm/tree/main/modules/azure-sa)
- [x] Allow backups and policies for shares
- [x] Allow backups and policies for blobs
- [x] Allow lifecycle policy rules for storage accounts
```
